# Generated by Django 4.2.29 on 2026-03-31 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacao', '0004_venda_perfil_itemvenda'),
    ]

    operations = [
        migrations.AddField(
            model_name='venda',
            name='status',
            field=models.CharField(choices=[('P', 'Pendente'), ('C', 'Concluída'), ('X', 'Cancelada')], default='P', max_length=1),
        ),
    ]
