# Generated by Django 4.2.29 on 2026-03-31 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacao', '0006_alter_venda_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='venda',
            name='cliente',
        ),
        migrations.DeleteModel(
            name='ItemVenda',
        ),
        migrations.DeleteModel(
            name='Perfil',
        ),
        migrations.DeleteModel(
            name='Produto',
        ),
        migrations.DeleteModel(
            name='Venda',
        ),
    ]
