# Generated by Django 4.2.29 on 2026-04-14 00:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('aplicacao', '0007_remove_perfil_cliente_remove_venda_cliente_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VibrationCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motor_id', models.CharField(default='MOTOR_01', max_length=50)),
                ('collected_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('vibration_data', models.JSONField(help_text='Lista JSON com 10000 valores de vibração (float)')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('processed', 'Processado (FFT gerado)'), ('error', 'Erro no processamento')], default='pending', max_length=20)),
            ],
            options={
                'ordering': ['-collected_at'],
            },
        ),
    ]
